# Configuration for new-pr-welcome - https://github.com/behaviorbot/new-pr-welcome

# Comment to be posted to on PRs from first time contributors in your repository
newPRWelcomeComment: >
  Thanks for opening this pull request!
  We have detected this is the first time for you to contribute
  to *fMRIPrep*.
  Please check out our [contributing guidelines](https://github.com/neurostuff/NiMARE/blob/master/CONTRIBUTING.md).

  We invite you to list yourself as a *fMRIPrep* contributor, so if your name
  is not already mentioned, please modify the
  [``.zenodo.json``](https://github.com/neurostuff/NiMARE/blob/master/.zenodo.json)
  file with your data right above Russ' entry. Example:

  ```

  {
     "name": "Contributor, New NiMARE",
     "affiliation": "Department of Psychology, Some University",
     "orcid": "<your id>"
  },

  {
     "name": "Salo, Taylor P.",
     "affiliation": "Department of Psychology, Florida International University",
     "orcid": "0000-0001-9813-3167"
  },

  ```


  Of course, if you want to opt out this time there is no
  problem at all with adding your name later.
  You will be always welcome to add it in the future whenever
  you feel it should be listed.
